function p = td_sharedcode_pathdef
% TD_SHAREDCODE_PATHDEF - some paths you might want - Tom's shared code
%
% In your startup.m (or at the command line)
%
% run('path/to/this/file/td_sharedcode_setup.m');
%
% This adds directories in Tom's shared code repository to your path
%
% Tom Davidson (tjd@stanford.edu/tjd@alum.mit.edu) May 2010

 
path_to_repo = pwd; % since we cd'd here before running this

p = [...
    path_to_repo '/:', ...
    path_to_repo '/cont:', ...
    path_to_repo '/import:', ...
    path_to_repo '/nlx:', ...
    genpath([path_to_repo '/obj']), ...
    path_to_repo '/util:', ...
    ...
];